### ISSUE TITLE
希望训练完成后导出pb模型用于部署

### ISSUE THREAD

**Issue by pbz123** [yaleimeng/TextClassify_with_BERT#1]
您好，请问代码里可以将我们的训练模型保存为.pb模型文件并且调用这个模型做相应的预测吗，如果方便希望您能更新一下，真的是万分的感谢

**Comment by yaleimeng** [comment]
感谢关注。暂时还没有做，不过有计划在未来加上。目前load *.ckpt文件是可以预测的。

**Comment by pbz123** [comment]
好的，期待您的更新，我会一直持续关注

**Comment by yaleimeng** [comment]
现在已经可以生成单个文件的.pb模型了。
可以用于serving部署，具体可阅读simple-tensorflow-serving的文档；也可以使用其他开源框架进行服务搭建。  @pbz123
