### ISSUE TITLE
预测速度太慢

### ISSUE THREAD

**Issue by xiaocmxiao** [yaleimeng/TextClassify_with_BERT#4]
预测速度太慢了，一个文本要3s左右，显存有占用，不清楚是不是因为 import train_eval占用的。predict没有用gpu吗？就算用cpu，也不会这么慢呀。请问下有知道原因的吗？

**Comment by xiaocmxiao** [comment]
我很确定，预测没有用gpu，我在只有cpu的机器上跑，就是3s左右。。。。。

**Comment by charlesXu86** [comment]
他是这个预测代码有问题，他没有初始化，所以每次预测都要初始化一次，所以预测特别慢

**Comment by xiaocmxiao** [comment]
是预测代码中：ele = list(result)[0]，这一句就要3s，这只是解析生成器，不明白为什么要这么久时间。。。

**Comment by xiaocmxiao** [comment]
@charlesXu86 是预测代码中：ele = list(result)[0]，这一句就要3s，这只是解析生成器，不明白为什么要这么久时间。。。

**Comment by charlesXu86** [comment]
我上午debug的时候也发现了，也没想明白

**Comment by xiaocmxiao** [comment]
@charlesXu86 你有换其他方式解析吗？我用循环的方式也是很慢，还有没有什么方法呢？

**Comment by charlesXu86** [comment]
> @charlesXu86 你有换其他方式解析吗？我用循环的方式也是很慢，还有没有什么方法呢？
我重新写了一个预测代码

**Comment by xiaocmxiao** [comment]
@charlesXu86 能否发我一份预测代码呢？ 707496721@qqcom

**Comment by charlesXu86** [comment]
> @charlesXu86 能否发我一份预测代码呢？ 707496721@qqcom

加我好友吧997562867

**Comment by LydiaLXH** [comment]
> > @charlesXu86 能否发我一份预测代码呢？ 707496721@qqcom
> 
> 加我好友吧997562867

能否也发我一份预测代码？非常感谢! 429267327@qq.com

**Comment by TianFuKang** [comment]
这个问题我解决了，使用的pb模型，需要的可以联系我

**Comment by allenxcp** [comment]
@TianFuKang  可以分享下你修改的code吗？或者如何修改的，邮箱 xcp119@163.com

**Comment by TianFuKang** [comment]
> @TianFuKang 可以分享下你修改的代码吗？或者如何修改的，邮箱[xcp119@163.com](mailto:xcp119@163.com)

https://blog.csdn.net/FK2016/article/details/106092844#comments_13691692
